title: Max Rudolph
description: My Website!!
url: https://maxrudolph1.github.io
baseurl: ""
repository: maxrudolph1/maxrudolph1.github.io
lang: en

author:
  name: Max Rudolph
  email: mrudolph@cs.utexas.edu
  affiliation: UT Austin
  advisor_name: Amy Zhang
  advisor_url: https://amyzhang.github.io/
  github: maxrudolph1
  twitter: maxbrudolph
  scholar: https://scholar.google.com/citations?user=G1a5cBkAAAAJ
  cv: /files/rudolph_cv.pdf

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge

permalink: pretty
timezone: America/Chicago
future: true

include:
  - files
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor
  - node_modules
  - LICENSE
  - "*.sublime-*"
  - maxrudolph_portrait-web-169.jpg
  - images/joshtree.png
  - images/frog.png
  - images/earth_day_chocolates.jpeg
  - images/newrivergorge.png
  - images/camera.png
  - images/olympic.png
  - images/shenandoah.png
  - images/greatsmokymountains.JPG
  - images/everglades.JPG
  - images/westvirginia.JPG

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-redirect-from

defaults:
  - scope:
      path: ""
    values:
      layout: default
